#!/bin/sh
# =============================================================================
# Runtime config injector for the OmniProctor SPA.
#
# Vite resolves env vars at build time, which means a baked image would be
# locked to a single API URL. To keep one image deployable across environments
# we instead emit a tiny /config.js on every container start and have the SPA
# read window.__APP_CONFIG__ (see src/api/client.js + index.html).
#
# Lives at /docker-entrypoint.d/40-write-runtime-config.sh because the
# nginx:alpine base image automatically executes everything in that directory
# before the daemon starts.
# =============================================================================

set -eu

API_BASE_URL="${API_BASE_URL:-}"
APP_NAME="${APP_NAME:-OmniProctor}"

OUTPUT="/usr/share/nginx/html/config.js"

# Strip any trailing slashes so callers don't have to worry about double-slash
# URLs ending up in <a href> attributes etc.
API_BASE_URL=$(printf '%s' "$API_BASE_URL" | sed 's:/*$::')

cat > "$OUTPUT" <<EOF
// Generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ").
// Do NOT commit edits to this file - they will be overwritten on next start.
window.__APP_CONFIG__ = Object.freeze({
  API_BASE_URL: "${API_BASE_URL}",
  APP_NAME: "${APP_NAME}"
});
EOF

if [ -z "$API_BASE_URL" ]; then
    echo "[entrypoint] WARNING: API_BASE_URL is empty - the SPA will fall back" >&2
    echo "[entrypoint]          to http://localhost:8001/api/v1 which only works" >&2
    echo "[entrypoint]          for local dev. Set API_BASE_URL in your compose" >&2
    echo "[entrypoint]          file or `docker run -e` flag." >&2
else
    echo "[entrypoint] Wrote $OUTPUT (API_BASE_URL=$API_BASE_URL)"
fi
